version: '3.8'

services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10"
      RAM_SIZE: "1G"
      CPU_CORES: "2"
      USERNAME: "jhone9669"
      PASSWORD: "124578"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006  # Web-based viewer para a instalação do Windows
      - 3389:3389/tcp  # RDP para acesso remoto
      - 8000:8000  # Porta do Django
    volumes:
      - /marinheirosorders:/data/marinheirosorders  # Mapeia o projeto Django para o Windows
