# Generated by Django 5.1.2 on 2024-10-23 00:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='dish_note',
        ),
        migrations.AlterField(
            model_name='dish',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(related_name='dishes', to='core.dish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
