# Generated by Django 5.1.2 on 2024-10-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_order_dishes_orderdish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdish',
            name='amount',
            field=models.FloatField(default=1),
        ),
    ]
